In [1]:
pwd

'C:\\Users\\AMAN236\\Music'

In [10]:
import pandas as pd

df = pd.read_csv('pokemon_data.csv')
#print first 3 lines
print(df.head(3))
#print last 3 lines
print(df.tail(3))

   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80

   Generation  Legendary
0           1      False
1           1      False
2           1      False
       #                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170
799  721            Volcanion     Fire  Water  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
797      130     70           6       True
798      130     80           6       True
799       90     70           6       True

# Reading data in pandas

In [32]:
##Read Headers
#print(df.columns)

##Read each Column
#print(df['Name'][0:5])

##Read multiple Column
#print(df[ ['Name','Type 1','HP'] ][0:7])

##Read each row ...(i.loc means index location)
#print(df.iloc[1])

#another way to itter through rows
#for index, row in df.iterrows():
 #   print(index,row['Name'])
    
#when you want to retrive data with specific type
df.loc[df['Type 2']=="Poison"]

##read a specific location (R,C).. r is row and c is column
#print(df.iloc[2,5])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
53,48,Venonat,Bug,Poison,60,55,50,40,55,45,1,False
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
78,72,Tentacool,Water,Poison,40,40,35,50,100,70,1,False
79,73,Tentacruel,Water,Poison,80,70,65,80,120,100,1,False
99,92,Gastly,Ghost,Poison,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
227,211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,False
292,269,Dustox,Bug,Poison,60,50,70,50,90,65,3,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
604,544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,False
605,545,Scolipede,Bug,Poison,60,100,89,55,69,112,5,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

# Sorting/Describing Data

In [43]:
##gives mean max min count values
#df.describe()

##sorting 

#df.sort_values(['Type 1'],ascending=True)

##Sorting on multiples cases..0 Will go high to low, 1 will go low to high
df.sort_values(['Type 1','HP'],ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

# Making Changes to the Data

In [58]:
#df.head(5)

##add new column with total addtion of row values

#df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
#df.head(5)

##easier way to do same ... " : " means all
df['Total'] = df.iloc[:,4:10].sum(axis=1)
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [61]:
#ALL THESE COMMAND DON'T REALLY MODIFY DATA AT ALL.. IS HELP VISUALIZE THE CHANGES

#AVOID HARDCOADING THE VALUES OF COLUMN AS BELOW ..BETTER TRY TO FETCH INDEX OF PARTICULAR COLUMN AND USE

# moving total column from one place to another
# cols[0:4] will get first 4 column in same order we want it
#cols[-1] reverse indexing to get the total 
#cols[4:12] 12 is the position  of the column need to be moved after 4th column
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]] + cols[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,False,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,False,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,False,309,39,52,43,60,50,65,1

# Saving  our Data (Exporting into Desired Format)

In [87]:
#SAVING DATA IN CSV FORMAT where we don't want index
df.to_csv('modified .csv',index=False)

In [88]:
#SAVING DATA IN excel FORMAT where we don't want index
df.to_excel('modified.xlsx', index=False)

In [89]:
#SAVING DATA IN txt FORMAT or TAB seperated format where we don't want index with seperator 
df.to_csv('modified.txt',index=False, sep='\t' )

# Filtering Data

In [71]:
# one filtering condition
df.loc[df['Type 1']== 'Grass']

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,False,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,False,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
48,43,Oddish,Grass,Poison,False,320,45,50,55,75,65,30,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,False,313,56,61,65,48,45,38,6
719,651,Quilladin,Grass,NaN,False,405,61,78,95,56,58,57,6
720,652,Chesnaught,Grass,Fighting,False,530,88,107,122,74,75,64,6
740,672,Skiddo,Grass,NaN,False,350,66,65,48,62,57,52,6
741,673,Gogoat,Grass,NaN,False,531,123,100,62,97,81,68,6

In [72]:
# Two filtering condition
df.loc[(df['Type 1']== 'Grass') & (df['Type 2']== 'Poison')]

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,False,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,False,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
48,43,Oddish,Grass,Poison,False,320,45,50,55,75,65,30,1
49,44,Gloom,Grass,Poison,False,395,60,65,70,85,75,40,1
50,45,Vileplume,Grass,Poison,False,490,75,80,85,110,90,50,1
75,69,Bellsprout,Grass,Poison,False,300,50,75,35,70,30,40,1
76,70,Weepinbell,Grass,Poison,False,390,65,90,50,85,45,55,1
77,71,Victreebel,Grass,Poison,False,490,80,105,65,100,70,70,1
344,315,Roselia,Grass,Poison,False,400,50,60,45,100,80,65,3
451,406,Budew,Grass,Poison,False,280,40,30,35,50,70,55,4
452,407,Roserade,Grass,Poison,False,515,60,70,65,125,105,90,4
651,590,Foongus,Grass,Poison,False,294,69,55,45,55,55,15,5
652,591,Amoonguss,Grass,Poison,False,464,114,85,70,85,80,30,5

In [73]:
# Multiple filtering condition
df.loc[(df['Type 1']== 'Grass') & (df['Type 2']== 'Poison') & (df['HP']>70) ]

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
50,45,Vileplume,Grass,Poison,False,490,75,80,85,110,90,50,1
77,71,Victreebel,Grass,Poison,False,490,80,105,65,100,70,70,1
652,591,Amoonguss,Grass,Poison,False,464,114,85,70,85,80,30,5

In [77]:
# To reset index for the data frame (df)

new_df= df.loc[(df['Type 1']== 'Grass') & (df['Type 2']== 'Poison') & (df['HP']>70) ]
new_df= new_df.reset_index()
new_df

,index,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
1,3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
2,50,45,Vileplume,Grass,Poison,False,490,75,80,85,110,90,50,1
3,77,71,Victreebel,Grass,Poison,False,490,80,105,65,100,70,70,1
4,652,591,Amoonguss,Grass,Poison,False,464,114,85,70,85,80,30,5

In [78]:
# when you want to search in a column which contain some "specific" words

df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
7,6,CharizardMega Charizard X,Fire,Dragon,False,634,78,130,111,130,85,100,1
8,6,CharizardMega Charizard Y,Fire,Flying,False,634,78,104,78,159,115,100,1
12,9,BlastoiseMega Blastoise,Water,NaN,False,630,79,103,120,135,115,78,1
19,15,BeedrillMega Beedrill,Bug,Poison,False,495,65,150,40,15,80,145,1
23,18,PidgeotMega Pidgeot,Normal,Flying,False,579,83,80,80,135,80,121,1
71,65,AlakazamMega Alakazam,Psychic,NaN,False,590,55,50,65,175,95,150,1
87,80,SlowbroMega Slowbro,Water,Psychic,False,590,95,75,180,130,80,30,1
102,94,GengarMega Gengar,Ghost,Poison,False,600,60,65,80,170,95,130,1
124,115,KangaskhanMega Kangaskhan,Normal,NaN,False,590,105,125,100,60,100,100,1
137,127,PinsirMega Pinsir,Bug,Flying,False,600,65,155,120,65,90,105,1
141,130,GyaradosMega Gyarados,Water,Dark,False,640,95,155,109,70,130,81,1
154,142,AerodactylMega Aerodactyl,Rock,Flying,False,615,80,135,85,70,95,150,1
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,True,780,106,190,100,154,100,130,1
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,True,780,106,150,70,194,120,140,1
168,154,Meganium,Grass,NaN,False,525,80,82,100,83,100,80,2
196,181,AmpharosMega Ampharos,Electric,Dragon,False,610,90,95,105,165,110,45,2
224,208,SteelixMega Steelix,Steel,Ground,False,610,75,125,230,55,95,30,2
229,212,ScizorMega Scizor,Bug,Steel,False,600,70,150,140,65,100,75,2
232,214,HeracrossMega Heracross,Bug,Fighting,False,600,80,185,115,40,105,75,2
248,229,HoundoomMega Houndoom,Dark,Fire,False,600,75,90,90,140,90,115,2
268,248,TyranitarMega Tyranitar,Rock,Dark,False,700,100,164,150,95,120,71,2
275,254,SceptileMega Sceptile,Grass,Dragon,False,630,70,110,75,145,85,145,3
279,257,BlazikenMega Blaziken,Fire,Fighting,False,630,80,160,80,130,80,100,3
283,260,SwampertMega Swampert,Water,Ground,False,635,100,150,110,95,110,70,3
306,282,GardevoirMega Gardevoir,Psychic,Fairy,False,618,68,85,65,165,135,100,3
327,302,SableyeMega Sableye,Dark,Ghost,False,480,50,85,125,85,115,20,3
329,303,MawileMega Mawile,Steel,Fairy,False,480,50,105,125,55,95,50,3
333,306,AggronMega Aggron,Steel,NaN,False,630,70,140,230,60,80,50,3
336,308,MedichamMega Medicham,Fighting,Psychic,False,510,60,100,85,80,85,100,3
339,310,ManectricMega Manectric,Electric,NaN,False,575,70,75,80,135,80,135,3
349,319,SharpedoMega Sharpedo,Water,Dark,False,560,70,140,70,110,65,105,3
354,323,CameruptMega Camerupt,Fire,Ground,False,560,70,120,100,145,105,20,3
366,334,AltariaMega Altaria,Dragon,Fairy,False,590,75,110,110,110,105,80,3
387,354,BanetteMega Banette,Ghost,NaN,False,555,64,165,75,93,83,75,3
393,359,AbsolMega Absol,Dark,NaN,False,565,65,150,60,115,60,115,3
397,362,GlalieMega Glalie,Ice,NaN,False,580,80,120,80,120,80,100,3
409,373,SalamenceMega Salamence,Dragon,Flying,False,700,95,145,130,120,90,120,3
413,376,MetagrossMega Metagross,Steel,Psychic,False,700,80,145,150,105,110,110,3
418,380,LatiasMega Latias,Dragon,Psychic,True,700,80,100,120,140,150,110,3
420,381,LatiosMega Latios,Dragon,Psychic,True,700,80,130,100,160,120,110,3
426,384,RayquazaMega Rayquaza,Dragon,Flying,True,780,105,180,100,180,100,115,3
476,428,LopunnyMega Lopunny,Normal,Fighting,False,580,65,136,94,54,96,135,4
494,445,GarchompMega Garchomp,Dragon,Ground,False,700,108,170,115,120,95,92,4
498,448,LucarioMega Lucario,Fighting,Steel,False,625,70,145,88,140,70,112,4
511,460,AbomasnowMega Abomasnow,Grass,Ice,False,594,90,132,105,132,105,30,4
527,475,GalladeMega Gallade,Psychic,Fighting,False,618,68,165,95,65,115,110,4
591,531,AudinoMega Audino,Normal,Fairy,False,545,103,60,126,80,126,50,5
796,719,DiancieMega Diancie,Rock,Fairy,True,700,50,160,110,160,110,110,6

In [79]:
#RegEx can be used to check if a string contains the specified search pattern.
# to ignore uppercase issue we can use FLAG "flags=re.I"
import re
df.loc[df['Type 1'].str.contains('fire|grass',flags=re.I, regex= True)]

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,False,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,False,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,False,309,39,52,43,60,50,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,False,369,62,50,58,73,54,72,6
736,668,Pyroar,Fire,Normal,False,507,86,68,72,109,66,106,6
740,672,Skiddo,Grass,NaN,False,350,66,65,48,62,57,52,6
741,673,Gogoat,Grass,NaN,False,531,123,100,62,97,81,68,6
799,721,Volcanion,Fire,Water,True,600,80,110,120,130,90,70,6

In [80]:
# * means zero or more  and ^ means it word should start with pi 
import re
df.loc[df['Name'].str.contains('^pi[a-z]*',flags=re.I, regex= True)]

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
20,16,Pidgey,Normal,Flying,False,251,40,45,40,35,35,56,1
21,17,Pidgeotto,Normal,Flying,False,349,63,60,55,50,50,71,1
22,18,Pidgeot,Normal,Flying,False,479,83,80,75,70,70,101,1
23,18,PidgeotMega Pidgeot,Normal,Flying,False,579,83,80,80,135,80,121,1
30,25,Pikachu,Electric,NaN,False,320,35,55,40,50,50,90,1
136,127,Pinsir,Bug,NaN,False,500,65,125,100,55,70,85,1
137,127,PinsirMega Pinsir,Bug,Flying,False,600,65,155,120,65,90,105,1
186,172,Pichu,Electric,NaN,False,205,20,40,15,35,35,60,2
219,204,Pineco,Bug,NaN,False,290,50,65,90,35,35,15,2
239,221,Piloswine,Ice,Ground,False,450,100,100,80,60,60,50,2
438,393,Piplup,Water,NaN,False,314,53,51,53,61,56,40,4
558,499,Pignite,Fire,Fighting,False,418,90,93,55,70,55,55,5
578,519,Pidove,Normal,Flying,False,264,50,55,50,36,30,43,5

# Conditional Changes

In [82]:
df.loc[df['Type 1']== 'Fire', 'Legendary']= True
df

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,False,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,False,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,True,309,39,52,43,60,50,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,True,600,50,100,150,100,150,50,6
796,719,DiancieMega Diancie,Rock,Fairy,True,700,50,160,110,160,110,110,6
797,720,HoopaHoopa Confined,Psychic,Ghost,True,600,80,110,60,150,130,70,6
798,720,HoopaHoopa Unbound,Psychic,Dark,True,680,80,160,60,170,130,80,6
799,721,Volcanion,Fire,Water,True,600,80,110,120,130,90,70,6

# Working with Large amount of Data

In [ ]:
#retrieving data in set of chunks
for df in pd.read_csv('modified.csv', chunksize=5):
    print("CHUNK DF")
    print(df)

In [86]:
pwd

'C:\\Users\\AMAN236\\Music'